apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanomq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanomq
  template:
    metadata:
      labels:
        app: nanomq
    spec:
      nodeSelector:
        worker: "1"
      containers:
        - name: nanomq
          image: docker.io/library/nanomq-with-exporter
          imagePullPolicy: Never
          ports:
            - name: mqtt
              containerPort: 1883
            - name: metrics
              containerPort: 9100
          volumeMounts:
            - name: log
              mountPath: /logs
          env:
            - name: NANOMQ_LOG_TO
              value: "file"
            - name: NANOMQ_LOG_LEVEL
              value: "info"
            - name: NANOMQ_LOG_DIR
              value: "/logs"
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: nanomq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nanomq
spec:
  selector:
    app: nanomq
  ports:
    - name: nanomq
      port: 1883
      targetPort: 1883
    - name: metrics
      port: 9100
      targetPort: 9100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanomq-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path